# Site settings

title: Olivia Duong
email: duongoli@uw.edu
description: UW MLIS 2023
url: "https://oliviasduong.github.io/"
github_username: oliviasduong

# Theme settings
theme: midnight
plugins:
  - jekyll-feed
